New apctl patch (Mladen Turk <mturk@jboss.org>	2015-05-30 07:28:46 (GMT)).

diff --git a/support/apachectl.in b/support/apachectl.in
--- a/support/apachectl.in
+++ b/support/apachectl.in
@@ -42,21 +42,34 @@ ARGV="$@"
 # --------------------                              --------------------
 # 
 # the path to your httpd binary, including options if necessary
-HTTPD='@exp_sbindir@/@progname@'
+HTTPD="@exp_sbindir@/@progname@"
+ROOTDIR="-d @installroot@/etc/httpd"
 #
-# pick up any necessary environment variables
-if test -f @exp_sbindir@/envvars; then
-  . @exp_sbindir@/envvars
-fi
 #
 # a command that outputs a formatted text version of the HTML at the
 # url given on the command line.  Designed for lynx, however other
 # programs may work.  
-LYNX="@LYNX_PATH@ -dump"
+#
+LYNX="`which lynx 2>/dev/null || echo none`"
+
+checklynx()
+{
+if [ "$LYNX" = "none" ]; then
+   echo "The 'lynx' package is required for this functionality."
+   exit 8
+fi
+}
+
 #
 # the URL to your server's mod_status status page.  If you do not
 # have one, then status and fullstatus will not work.
 STATUSURL="http://localhost:@PORT@/server-status"
+
+# Source @installroot@/etc/sysconfig/httpd for $HTTPD setting, etc.
+if [ -r "@installroot@/etc/sysconfig/httpd" ]; then
+   . "@installroot@/etc/sysconfig/httpd"
+fi
+
 #
 # Set this variable to a command that increases the maximum
 # number of file descriptors allowed per child process. This is
@@ -77,28 +90,32 @@ if [ "x$ARGV" = "x" ] ; then
 fi
 
 case $ACMD in
-start|stop|restart|graceful|graceful-stop)
-    $HTTPD -k $ARGV
+start|stop|graceful-stop)
+    $HTTPD $ROOTDIR $OPTIONS -k $ARGV
     ERROR=$?
     ;;
-startssl|sslstart|start-SSL)
-    echo The startssl option is no longer supported.
-    echo Please edit httpd.conf to include the SSL configuration settings
-    echo and then use "apachectl start".
-    ERROR=2
+restart|graceful)
+    if $HTTPD $ROOTDIR $OPTIONS -t >/dev/null 2>&1; then
+       $HTTPD $ROOTDIR $OPTIONS -k $ARGV
+    else
+       echo "apachectl: Configuration syntax error, will not run \"$ARGV\":"
+       $HTTPD $ROOTDIR -t
+    fi
     ;;
 configtest)
-    $HTTPD -t
+    $HTTPD $ROOTDIR -t
     ERROR=$?
     ;;
 status)
-    $LYNX $STATUSURL | awk ' /process$/ { print; exit } { print } '
+    checklynx
+    $LYNX -dump $STATUSURL | awk ' /process$/ { print; exit } { print } '
     ;;
 fullstatus)
-    $LYNX $STATUSURL
+    checklynx
+    $LYNX -dump $STATUSURL
     ;;
 *)
-    $HTTPD "$@"
+    $HTTPD $ROOTDIR $OPTIONS $ARGV
     ERROR=$?
 esac
 
